WARNFLAGS= -Wsystem-headers -Wall -W -Wno-unused-parameter \
	-Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith \
	-Wold-style-definition -Wreturn-type -Wwrite-strings \
	-Wswitch -Wshadow -Wcast-align -Wchar-subscripts \
	-Winline -Wnested-externs

CFLAGS= -g3 -O0 $(WARNFLAGS)
CC?= gcc

all:
	$(CC) $(CFLAGS) de2lcd.c de2lcd_if.c -o de2lcd

clean:
	rm -f de2lcd

realclean: clean
	rm -f *~ *.bak
