#Master email address and password
admin:
    username: prw@soton.ac.uk
    password: $2a$10$KVIbro1v6wwL0CoHYt.L2.EQab4kGVTWdmRgz2YRV4SEe56PQErNG
    permission: 0 
#Maximum permission in the databse

database:
    type: mysql
    user: root
    password: chip1234
    database_name: ChipTester
    address: localhost

#### Sending email configuration

email:
    email_enable: yes
#Configuration of the account to send emails to
    username: soton.chiptester@gmail.com
    smtpaddress: smtp.gmail.com #The smtp server where the email is sent.
    port: 587
    domain: localhost
    password: chip1234
    authentication: plain
    enable_ttls: true

web:
    server_address: http://0.0.0.0:4567/
