source :rubygems

gem 'rake', "~> 0.9.2"
gem 'data_mapper', "~> 1.2.0"
gem 'dm-sqlite-adapter', "~> 1.2.0"
gem 'sinatra', "~> 1.3.2"
gem 'json', "~> 1.6.6"
gem 'sass', "~> 3.1.15"
gem 'sinatra-flash', "~> 0.3.0"
gem 'bcrypt-ruby', "~>3.0.1"
gem 'mail', "~> 2.4.4"
gem "unicorn", "~> 4.2.1"

