# TCL File Generated by Component Editor 11.1sp1
# Wed May 02 18:08:50 BST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | freq_counter "freq_counter" v1.0
# | null 2012.05.02.18:08:50
# | 
# | 
# | /home/alex/ChipTester/hdl/ip/freq_counter/freq_counter.sv
# | 
# |    ./fc_control.sv syn, sim
# |    ./fc_mux.sv syn, sim
# |    ./freq_counter.sv syn, sim
# |    ./freq_measurement.sv syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module freq_counter
# | 
set_module_property NAME freq_counter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME freq_counter
set_module_property TOP_LEVEL_HDL_FILE freq_counter.sv
set_module_property TOP_LEVEL_HDL_MODULE freq_counter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME freq_counter
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file fc_control.sv {SYNTHESIS SIMULATION}
add_file fc_mux.sv {SYNTHESIS SIMULATION}
add_file freq_counter.sv {SYNTHESIS SIMULATION}
add_file freq_measurement.sv {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter ADDR_WIDTH INTEGER 8
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 8
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH ENABLED false
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH ENABLED false
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter NREGS INTEGER 5
set_parameter_property NREGS DEFAULT_VALUE 5
set_parameter_property NREGS DISPLAY_NAME NREGS
set_parameter_property NREGS TYPE INTEGER
set_parameter_property NREGS ENABLED false
set_parameter_property NREGS UNITS None
set_parameter_property NREGS AFFECTS_GENERATION false
set_parameter_property NREGS HDL_PARAMETER true
add_parameter NDESIGNS INTEGER 24
set_parameter_property NDESIGNS DEFAULT_VALUE 24
set_parameter_property NDESIGNS DISPLAY_NAME NDESIGNS
set_parameter_property NDESIGNS TYPE INTEGER
set_parameter_property NDESIGNS UNITS None
set_parameter_property NDESIGNS AFFECTS_GENERATION false
set_parameter_property NDESIGNS HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 32
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 1
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address address Input ADDR_WIDTH
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 readdatavalid readdatavalid Output 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink

set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end in_signal export Input NDESIGNS
add_interface_port conduit_end busy export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink Clock clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges NONE

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink nResetIn reset_n Input 1
# | 
# +-----------------------------------
