WARNFLAGS= -Wsystem-headers -Wall -W -Wno-unused-parameter \
	-Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith \
	-Wold-style-definition -Wreturn-type -Wwrite-strings \
	-Wswitch -Wshadow -Wcast-align -Wchar-subscripts \
	-Winline -Wnested-externs

CFLAGS= -g3 -O0 $(WARNFLAGS)
CC?= gcc

OBJS= confrd.o trunner_if.o sram.o req.o log.o parser_common.o parser_vec.o parser_cfg.o


all: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o confrd

clean:
	rm -f confrd $(OBJS)

realclean: clean
	rm -f *~ *.bak
