/*
 * This header is generated by sopc2dts
 * Sopc2dts is written by Walter Goossens <waltergoossens@home.nl>
 * in cooperation with the nios2 community <Nios2-dev@sopc.et.ntust.edu.tw>
 */
#ifndef CUSTOM_FPGA_H_
#define CUSTOM_FPGA_H_

/* generated from linuxsys.sopcinfo */

/* Dumping slaves of cpu.data_master*/

/* cpu.jtag_debug_module is a altera_nios2_qsys */
#define CONFIG_SYS_CLK_FREQ	100000000
#define CONFIG_SYS_DCACHE_SIZE	32768
#define CONFIG_SYS_DCACHELINE_SIZE	32
#define CONFIG_SYS_ICACHELINE_SIZE	32
#define CONFIG_SYS_EXCEPTION_ADDR	0xc0000020
#define CONFIG_SYS_ICACHE_SIZE	65536
#define CONFIG_SYS_RESET_ADDR	0xc0000000
#define IO_REGION_BASE	0xE0000000

/* sdram_0.s1 is a altera_avalon_new_sdram_controller */
#define CONFIG_SYS_SDRAM_BASE	0xC0000000
#define CONFIG_SYS_SDRAM_SIZE	0x08000000

/* jtag_uart.avalon_jtag_slave is a altera_avalon_jtag_uart */
//#define CONFIG_SYS_JTAG_UART_BASE	0xE80034B0
#define CONFIG_SYS_UART_BASE		0xED100000
#define CONFIG_SYS_UART_FREQ		100000000
#define CONFIG_SYS_UART_BAUD		115200

#define LED_PIO_WIDTH 0

/* timer.s1 is a altera_avalon_timer */
#define CONFIG_SYS_TIMER_IRQ	1
#define CONFIG_SYS_TIMER_FREQ	100000000
#define CONFIG_SYS_TIMER_BASE	0xE8003480

/* altpll_0.pll_slave is a altpll */
#define ALTPLL_0_BASE	0xE80034A0

/* tse_mac.tx_csr is a triple_speed_ethernet */
#define CONFIG_SYS_ALTERA_TSE_RX_FIFO	2048
#define CONFIG_SYS_ALTERA_TSE_SGDMA_TX_BASE	0xE8003400
#define CONFIG_SYS_ALTERA_TSE_SGDMA_RX_BASE	0xE8003440
#define CONFIG_SYS_ALTERA_TSE_TX_FIFO	2048
#define CONFIG_SYS_ALTERA_TSE_DESC_SIZE	0x00001000
#define CONFIG_SYS_ALTERA_TSE_MAC_BASE	0xE8003000
#define CONFIG_SYS_ALTERA_TSE_DESC_BASE	0xE8001000
#define CONFIG_ALTERA_TSE
#define CONFIG_MII
#define CONFIG_CMD_MII
#define CONFIG_SYS_ALTERA_TSE_PHY_ADDR 1
#define CONFIG_SYS_ALTERA_TSE_FLAGS 0

/* usb.hc is a ISP1362_IF */
#define USB_HC	0xE82224D8
#define USB_DC	0xE82224E0
#define USB_HC_IRQ	5
#define USB_DC_IRQ	6

/* ISP1362_IF_0.hc is a ISP1362_IF */
#define ISP1362_IF_0_HC	0xE8221000
#define ISP1362_IF_0_DC	0xE8221008
#define ISP1362_IF_0_HC_IRQ	9
#define ISP1362_IF_0_DC_IRQ	10

/* cfi_flash_0.uas is a altera_generic_tristate_controller */
//#define CONFIG_SYS_FLASH_BASE	0x0A000000
#define CONFIG_SYS_FLASH_BASE 0xEA000000
#define CONFIG_FLASH_CFI_DRIVER
#define CONFIG_SYS_CFI_FLASH_STATUS_POLL /* fix amd flash issue */
#define CONFIG_SYS_FLASH_CFI
#define CONFIG_SYS_FLASH_USE_BUFFER_WRITE
#define CONFIG_SYS_FLASH_PROTECTION
#define CONFIG_SYS_MAX_FLASH_BANKS 1
#define CONFIG_SYS_MAX_FLASH_SECT 1024

#define CONFIG_BOOTDELAY	5

#define CONFIG_CMD_JFFS2
#define CONFIG_CMD_MTDPARTS     /* mtdparts command line support */
#define CONFIG_MTD_DEVICE       /* needed for mtdparts commands */
#define CONFIG_FLASH_CFI_MTD
#define MTDIDS_DEFAULT          "nor0=flash-0"

/* default mtd partition table */
#define MTDPARTS_DEFAULT        "mtdparts=flash-0:256k(u-boot),"\
                                "64k(u-boot_cfg),1728k(kernel),5632k(rootfs),512k(config)"


#define MMC_SPI_BASE 0xEBA10000
#define CONFIG_SYS_ALTERA_SPI_LIST { MMC_SPI_BASE }
#define CONFIG_ALTERA_SPI
#define CONFIG_CMD_SPI
#define CONFIG_CMD_MMC
#define CONFIG_MMC
#define CONFIG_GENERIC_MMC
#define CONFIG_CMD_MMC_SPI
#define CONFIG_MMC_SPI
#define CONFIG_MMC_SPI_BUS 0
#define CONFIG_MMC_SPI_CS 0
#define CONFIG_MMC_SPI_SPEED 2000000
#define CONFIG_MMC_SPI_MODE SPI_MODE_3
#define CONFIG_CMD_FAT
#define CONFIG_DOS_PARTITION

/* sysid_qsys_0.control_slave is a altera_avalon_sysid_qsys */
#define CONFIG_SYS_SYSID_BASE	0xEBA00000

/* spi_0.spi_control_port is a altera_avalon_spi */
#define SPI_0_BASE	0xEBA10000
#define SPI_0_IRQ	0

/* sram_bridge.avalon_slave_0 is a sram_bridge_16 */
#define SRAM_BRIDGE_BASE	0xEC000000




#define CONFIG_EXTRA_ENV_SETTINGS       "unlock=yes\0" \
                                        "nor0=flash-0\0"\
                                        "mtdparts=mtdparts=flash-0:"\
					"256k(u-boot),64k(u-boot_cfg),1728k(kernel),5632k(rootfs),512k(config)\0"


#endif	//CUSTOM_FPGA_H_
